"""
SQLAlchemy declarative foundation — two-layer design.

Layer 1 — Base (DeclarativeBase)
    The single metadata registry for the whole application.
    Alembic targets `Base.metadata` for autogenerate.
    Nothing else belongs here.

Layer 2 — BaseEntity (abstract ORM model)
    Every business model inherits from BaseEntity, NOT directly from Base.
    Centralises the UUID primary key and audit timestamps so they never
    have to be repeated.  Future cross-cutting concerns (soft-delete,
    optimistic locking, row-level audit) are added here once and
    automatically available to every model.

Import guide
------------
    # All application models
    from app.db.base import Base, BaseEntity
"""
import uuid
from datetime import datetime, timezone

from sqlalchemy import DateTime, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _utcnow() -> datetime:
    """Return the current UTC datetime (timezone-aware)."""
    return datetime.now(tz=timezone.utc)


# ---------------------------------------------------------------------------
# Layer 1 — metadata registry
# ---------------------------------------------------------------------------

class Base(DeclarativeBase):
    """
    Declarative base — owns the shared MetaData instance.

    Do NOT add columns or behaviour here.  This class exists solely so
    that `Base.metadata` can be passed to Alembic and `Base.registry` is
    shared across the whole application.
    """


# ---------------------------------------------------------------------------
# Layer 2 — shared abstract entity
# ---------------------------------------------------------------------------

class BaseEntity(Base):
    """
    Abstract base for every business model.

    Provides
    --------
    id : uuid.UUID
        Version-4 UUID primary key.  Generated by Python on insert and
        also has a DB-side server_default for raw SQL inserts.
    created_at : datetime
        Timezone-aware UTC timestamp set once at row creation.
    updated_at : datetime
        Timezone-aware UTC timestamp refreshed automatically on every UPDATE.

    Extension points
    ----------------
    Add soft-delete, optimistic-locking version columns, or tenant_id here
    when the time comes — every model inherits them for free.
    """

    __abstract__ = True

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid(),
        nullable=False,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=_utcnow,
        server_default=func.now(),
        nullable=False,
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=_utcnow,
        server_default=func.now(),
        onupdate=_utcnow,
        nullable=False,
    )
